spring:
  application:
    name: Order API
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8081
  servlet:
    context-path: /orderapi

#Health and Metrics
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics